# Google Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fairtestai-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Auto-scale configuration
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '5'
        # Cloud SQL connection (will be updated during deployment)
        run.googleapis.com/cloudsql-instances: 'PROJECT_ID:REGION:fairtestai-db'
        # Request timeout (5 minutes for long-running pipeline tasks)
        run.googleapis.com/client-name: 'terraform'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      serviceAccountName: fairtestai-sa
      containers:
      - image: gcr.io/PROJECT_ID/fairtestai-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # App configuration
        - name: FAIRTESTAI_ENV
          value: 'production'
        - name: FAIRTESTAI_PORT
          value: '8080'
        - name: FAIRTESTAI_LOG_LEVEL
          value: 'INFO'
        # Database (Cloud SQL)
        - name: FAIRTESTAI_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: url
        # API Keys (from Secret Manager)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-api-key
              key: key
        - name: GOOGLE_AI_KEY
          valueFrom:
            secretKeyRef:
              name: google-ai-key
              key: key
        - name: GROK_API_KEY
          valueFrom:
            secretKeyRef:
              name: grok-api-key
              key: key
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: mistral-api-key
              key: key
        # Storage (Cloud Storage bucket)
        - name: FAIRTESTAI_FILE_STORAGE_BUCKET
          value: 'fairtestai-files'
        - name: FAIRTESTAI_PIPELINE_ROOT
          value: '/tmp/pipeline_runs'
        # Security
        - name: FAIRTESTAI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret-key
              key: key
        - name: FAIRTESTAI_ENABLE_DEV_TOOLS
          value: 'false'
        - name: FAIRTESTAI_AUTO_APPLY_MIGRATIONS
          value: 'true'
        resources:
          limits:
            cpu: '2'
            memory: '2Gi'
          requests:
            cpu: '1'
            memory: '1Gi'
