"""Add wrong_answer and wrong_reason fields to Question model

Revision ID: a5fc3a61718f
Revises: f754d45f697f
Create Date: 2025-07-26 20:59:24.990163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fc3a61718f'
down_revision = 'f754d45f697f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wrong_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wrong_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('wrong_reason')
        batch_op.drop_column('wrong_answer')

    # ### end Alembic commands ###
