"""add updated_at/is_deleted/deleted_at on assessments and create jobs table

Revision ID: 310bfa3111f6
Revises: 3933c0337f44
Create Date: 2025-08-25 11:58:15.585523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '310bfa3111f6'
down_revision = '3933c0337f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('new_assessment_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_jobs_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['new_assessment_id'], ['assessments.id'], name=op.f('fk_jobs_new_assessment_id_assessments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    # Add columns with defaults first to avoid NOT NULL violations
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        # Drop legacy column if exists in DB
        batch_op.drop_column('copy_allowed')

    # Backfill updated_at with created_at where null, and is_deleted false
    op.execute("UPDATE assessments SET updated_at = COALESCE(updated_at, created_at), is_deleted = COALESCE(is_deleted, false) WHERE updated_at IS NULL OR is_deleted IS NULL")

    # Make columns non-nullable and drop server defaults
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(), server_default=None, nullable=False)
        batch_op.alter_column('is_deleted', existing_type=sa.Boolean(), server_default=None, nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy_allowed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    op.drop_table('jobs')
    # ### end Alembic commands ###
