"""Remove unique constraint from questions table

Revision ID: 3933c0337f44
Revises: a5fc3a61718f
Create Date: 2025-08-06 09:07:24.589104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3933c0337f44'
down_revision = 'a5fc3a61718f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('q_number',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_questions_assessment_qnum'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_questions_assessment_qnum'), ['assessment_id', 'q_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('q_number',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
