"""initial schema

Revision ID: f754d45f697f
Revises: 
Create Date: 2025-06-17 12:18:21.856656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f754d45f697f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('path', name=op.f('uq_stored_files_path'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('attack_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('original_pdf_id', sa.UUID(), nullable=True),
    sa.Column('answers_pdf_id', sa.UUID(), nullable=True),
    sa.Column('attacked_pdf_id', sa.UUID(), nullable=True),
    sa.Column('report_pdf_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['answers_pdf_id'], ['stored_files.id'], name=op.f('fk_assessments_answers_pdf_id_stored_files')),
    sa.ForeignKeyConstraint(['attacked_pdf_id'], ['stored_files.id'], name=op.f('fk_assessments_attacked_pdf_id_stored_files')),
    sa.ForeignKeyConstraint(['original_pdf_id'], ['stored_files.id'], name=op.f('fk_assessments_original_pdf_id_stored_files')),
    sa.ForeignKeyConstraint(['report_pdf_id'], ['stored_files.id'], name=op.f('fk_assessments_report_pdf_id_stored_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('q_number', sa.Integer(), nullable=False),
    sa.Column('stem_text', sa.Text(), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gold_answer', sa.Text(), nullable=False),
    sa.Column('gold_reason', sa.Text(), nullable=True),
    sa.Column('attacked_stem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_questions_assessment_id_assessments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('assessment_id', 'q_number', name='uq_questions_assessment_qnum')
    )
    op.create_table('llm_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('llm_answer', sa.Text(), nullable=False),
    sa.Column('llm_reason', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_llm_responses_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_responses')),
    sa.UniqueConstraint('question_id', 'model_name', name='uq_llmresponses_question_model')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_responses')
    op.drop_table('questions')
    op.drop_table('assessments')
    op.drop_table('stored_files')
    # ### end Alembic commands ###
